In [1]:
import numpy as np

In [2]:
my_list = [1,2,3]
arr = np.array(my_list)
arr

array([1, 2, 3])

In [4]:
my_mat = [[1,2,3],[4,5,6],[7,8,9]]
np.array(my_mat)

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [7]:
np.arange(0,7,2)

array([0, 2, 4, 6])

In [9]:
np.ones((2,3))

array([[1., 1., 1.],
       [1., 1., 1.]])

In [12]:
np.linspace(0,3,6)

array([0. , 0.6, 1.2, 1.8, 2.4, 3. ])

In [17]:
np.eye(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [19]:
np.random.rand(3,4)

array([[0.00337391, 0.2533748 , 0.58488536, 0.68924841],
       [0.84724417, 0.90318674, 0.24149244, 0.82978818],
       [0.88802588, 0.55984385, 0.61675437, 0.81713288]])

In [21]:
np.random.randn(4,3)

array([[-1.8512857 ,  1.12732794,  0.13498792],
       [-0.5806275 , -0.9454523 , -0.80059568],
       [-0.72359277,  0.53695737,  0.70712725],
       [ 0.714616  ,  0.08103941,  0.37291397]])

In [30]:
np.random.randint(3,100,2)

array([34, 96])

In [31]:
ranarr = np.random.randint(0,50,10)
ranarr

array([41, 10, 31, 39, 49, 16,  1, 13,  6, 26])

In [32]:
arr

array([1, 2, 3])

In [37]:
ranarr.max()

49

In [39]:
ranarr.argmax()

4

In [40]:
ranarr.min()

1

In [41]:
ranarr.argmin()

6

In [42]:
ranarr.shape

(10,)

In [44]:
arr.shape

(3,)

In [45]:
arr = np.arange(0,11)
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [50]:
arr[1:4]

array([1, 2, 3])

In [51]:
arr_2d = np.array([[5,10,15],[20,25,30],[35,40,45]])
arr_2d

array([[ 5, 10, 15],
       [20, 25, 30],
       [35, 40, 45]])

In [57]:
arr_2d[2,1]

40

In [72]:
arr_2d[:2,1:]

array([[10, 15],
       [25, 30]])

In [73]:
arr[arr>5]

array([ 6,  7,  8,  9, 10])

In [74]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])